esphome:
  name: esp-fan-controller

esp8266:
  board: nodemcuv2


# Enable Home Assistant API
api:
  encryption:
    key: "your-key-goes-here"

ota:
  password: "your-pass-goes-here"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "ESP-Fan-Controller"
    password: "rcLd0KlPnRkj"
   
captive_portal:
    
    
###### Fan RPM Sensor #####
sensor:
  - platform: pulse_counter
    pin: 
      number: D1
      mode: INPUT_PULLUP
    unit_of_measurement: 'RPM'
    id: office_fan_speed
    name: "Office Fan Speed"
    filters:
      - multiply: 0.5
    accuracy_decimals: 0
    update_interval: 10s

##### Debug for Wifi ####
  - platform: wifi_signal
    name: "WiFi Signal Sensor"
    update_interval: 60s

    
##### PWM Control #####
output:
  - platform: esp8266_pwm
    pin: D2
    frequency: 25000 Hz
    id: pwm_fan_output_blue


##### Fan Control #####
fan:
  - platform: speed
    output: pwm_fan_output_blue
    name: "PWM Fan Blue"
    speed_count: 100